---
title: "Advanced ggplots"
author: "Daeshik Park"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggalt)
library(gganimate)
library(ggExtra)
options(scipen=999)  # turn-off scientific notation like 1e+48
data("mpg")
```

<br>

### Scatterplot with Encircling

```{r, scatterplot With encircling}
mpg_2535 <- mpg %>% filter(cty > 25 & hwy > 35)
ggplot(data = mpg, aes(x = cty, y = hwy)) +
  geom_point(aes(color = class, size = cyl)) +
  coord_cartesian(xlim = c(0, 40), ylim = c(0, 50)) +
  geom_encircle(data = mpg_2535, aes(x = cty, y = hwy), 
                color = "red", size = 2, expand = 0.1) +
  labs(title = "Scatter Plot",
       subtitle = "MPG: City vs Highway",
       x = "City",
       y = "Highway",
       caption = "Source: mpg") +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5))
```

<br>

### Animations

```{r, animation in states}
#ggplot(data = mpg, aes(x = cty, y = hwy)) +
  #geom_point(aes(color = class, size = cyl)) +
  #transition_states(class, transition_length = 2, state_length = 1) +
  #labs(title = "State: {closest_state}")
```

```{r, animation in time}
gg1 <- ggplot(mpg, aes(cty, hwy, size = cyl, color = drv)) +
  geom_point(show.legend = FALSE) +
  scale_color_viridis_d() +
  scale_size(range = c(2, 12)) +
  scale_x_log10()
gg1 + facet_wrap( ~ class) +
  transition_time(year) +
  labs(title = "Year: {frame_time}")
```

<br>

### Marginal Histogram/Boxplot

```{r, marginal histogram}
gg2 <- ggplot(data = mpg, aes(x = cty, y = hwy)) +
  geom_jitter(aes(color = class, size = cyl), show.legend = FALSE) +
  geom_smooth()
ggMarginal(gg2, type = "histogram", fill = "green")
```



<br>

### *The End*


